# Generated by Django 3.2.5 on 2021-07-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_orderposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
